# Generated by Django 5.0.7 on 2024-07-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstproject',
            old_name='descripotion',
            new_name='description',
        ),
    ]
